version: '3'
services:
  foundry:
    build: docker/foundry
    volumes:
      - ${DATA_DIR}:/home/foundry/data
      - ${APP_DIR}:/home/foundry/install
    restart: unless-stopped

  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=${DOMAIN_URL}
      - VALIDATION=http
    volumes:
      - ./docker/nginx/default.conf:/config/nginx/site-confs/default
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped