version: '3'
services:
  foundry:
    build: docker/foundry
    volumes:
      - ${DATA_DIR}:/home/foundry/data
      - ${APP_DIR}:/home/foundry/install
    restart: unless-stopped

  nginx:
    image: nginx
    ports:
      - 80:80
      - 433:433
    volumes:
        - ./docker/nginx/:/etc/nginx/conf.d/
    restart: unless-stopped